# action.yml
name: 'Firebase - Copy Auth'
description: 'Copies Firebase Authentication users form one project to another'
inputs:
  source-project:  # id of project to read users
    description: 'Source project'
    required: true
  destination-project:  # id of project to write users
    description: 'Destination project'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source-project }}
    - ${{ inputs.destination-project }}