# action.yml
name: 'Firebase - Delete Auth'
description: 'Deletes all Firebase Authentication users form a given project'
inputs:
  project-id:  # id of project to delete users
    description: 'Firebase Project id'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-id }}
